services:
  ukge-simulator:
    build: .
    ports:
      - "8504:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      # Mount source code for development (optional, remove for production)
      - ./src:/app/src:ro
      - ./data:/app/data:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a development service that doesn't use Docker build
  # Useful for faster iteration during development
  dev:
    image: python:3.11-slim
    working_dir: /app
    ports:
      - "8502:8501"
    volumes:
      - .:/app
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    command: |
      bash -c "
        apt-get update && apt-get install -y curl &&
        pip install -r requirements.txt &&
        streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0
      "
    profiles:
      - dev
